services:
  - type: web
    name: lodge-review
    env: python
    buildCommand: ""
    startCommand: gunicorn lodge_review_project.wsgi:application
    preDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false
