# Generated by Django 5.2 on 2025-06-20 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 20, 10, 49, 20, 348999, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
